# -*- coding: utf-8 -*-
"""Assignment 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tZo30qt6GI6vNIfjje_gDGCiaUp7AoYV
"""

#Enter first and last name
firstname = input("Enter first name ")

lastname = input("Enter last name ")


#Enter your goals for this class
print("What are your goals for this class - long term goals?")
longterm = input('My longterm goal ')
print("my short term goals ")
goal1 = input("Enter goal 1 ")
goal2 = input("Enter goal 2 ")
goal3 = input("Enter goal 3 ")
goal4 = input("Enter goal 4" )
print()
print("First Name: " + firstname + " Last Name: " + lastname)
print(longterm)
print(goal1)
print(goal2)
print(goal3)
print(goal4)